[package]
name = "containerd-shim-spin-v2"
version = "0.13.1"
authors = ["SpinKube Engineering Team"]
edition = "2021"
repository = 'https://github.com/spinkube/containerd-shim-spin'
license = "Apache-2.0"
homepage = 'https://github.com/spinkube/containerd-shim-spin'
description = """
Containerd shim for running Spin workloads.
"""

[dependencies]
containerd-shim-wasm = { git = "https://github.com/containerd/runwasi", rev = "c04170e81794b1a776c840ffa765b3491d43445a" }
containerd-shim = "0.7.1"
log = "0.4"
spin-app = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
spin-core = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
spin-componentize = { git = "https://github.com/fermyon/spin-componentize", rev = "191789170abde10cd55590466c0660dd6c7d472a" }
# Enable loading components precompiled by the shim
spin-trigger = { git = "https://github.com/fermyon/spin", tag = "v2.3.1", features = ["unsafe-aot-compilation"] }
spin-trigger-http = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
spin-trigger-redis = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
trigger-sqs = { git = "https://github.com/fermyon/spin-trigger-sqs", rev = "ad7c5405d588161ce4ac317172dd8b165bdab572" }
trigger-command = { git = "https://github.com/fermyon/spin-trigger-command", rev = "b648a79ddd281ec8288842771930529cd98bf1aa" }
spin-manifest = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
spin-loader = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
spin-oci = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
spin-common = { git = "https://github.com/fermyon/spin", tag = "v2.3.1" }
wasmtime = "18.0.1"
tokio = { version = "1", features = ["rt"] }
openssl = { version = "*", features = ["vendored"] }
serde = "1.0"
serde_json = "1.0"
url = "2.3"
anyhow = "1.0"
oci-spec = { version = "0.6.3" }
futures = "0.3"
ctrlc = { version = "3.2", features = ["termination"] }


[dev-dependencies]
wat = "1"
