[package]
name = "containerd-shim-spin-v2"
version = "0.10.0"
authors = ["DeisLabs Engineering Team"]
edition = "2021"
repository = 'https://github.com/spinkube/containerd-shim-spin'
license = "Apache-2.0"
homepage = 'https://github.com/spinkube/containerd-shim-spin'
description = """
Containerd shim for running Spin workloads.
"""

[dependencies]
# containerd-shim-wasm = { git = "https://github.com/containerd/runwasi", rev = "c768e5b0919ca02903a301bf82a390489437dabe" }
containerd-shim-wasm = { path = "../../../containerd/runwasi/crates/containerd-shim-wasm" }
log = "0.4"
spin-app = {path = "../../../fermyon/spin/crates/app" }
spin-core = { path = "../../../fermyon/spin/crates/core"}
spin-componentize = { git = "https://github.com/fermyon/spin-componentize", rev = "191789170abde10cd55590466c0660dd6c7d472a" }
spin-trigger = { path = "../../../fermyon/spin/crates/trigger"}
spin-trigger-http = { path = "../../../fermyon/spin/crates/trigger-http"}
spin-trigger-redis = { path = "../../../fermyon/spin/crates/trigger-redis"}
trigger-sqs = { git = "https://github.com/fermyon/spin-trigger-sqs", tag = "v0.6.0" }
spin-manifest = { path = "../../../fermyon/spin/crates/manifest"}
spin-loader = { path = "../../../fermyon/spin/crates/loader"}
spin-oci = { path = "../../../fermyon/spin/crates/oci"}
spin-common = { path = "../../../fermyon/spin/crates/common"}
wasmtime = "17.0.0"
tokio = { version = "1", features = ["rt"] }
openssl = { version = "*", features = ["vendored"] }
serde = "1.0"
serde_json = "1.0"
url = "2.3"
anyhow = "1.0"
oci-spec = { version = "0.6.3" }
